# Zadanie 1: Predykcja jakości białego wina

In [54]:
import numpy as np
import pandas as pd

from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score,cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

import optuna

In [32]:
data = pd.read_csv("../Data/winequality-white.csv",sep=';')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [34]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

## Data Preparation

In [35]:
X = data.drop(['quality'],axis=1)
y = data['quality']

y.value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,shuffle=False,random_state=42)

X_train.shape

(3428, 11)

In [37]:
y.value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [38]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [45]:
def objective(trial:optuna.trial.Trial,regressor_name:str):
    n_features = trial.suggest_int("n_features",5,X_train.shape[1])
    
    if regressor_name == "RandomForest":
        n_estimators = trial.suggest_int("n_estimators",50,300)
        max_depth = trial.suggest_int("max_depth",3,20)
        min_samples_split = trial.suggest_int("min_samples_split",2,20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1,10)

        regressor = RandomForestRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
        )
        
    elif regressor_name == "KNN":
        n_neighbors = trial.suggest_int("n_neighbors",1,5)
        regressor = KNeighborsRegressor(
            n_neighbors=n_neighbors
        )
    else:
        return
    
    pipeline = Pipeline([
        ("StandardScaler",StandardScaler()),
        ("SelectKBest", SelectKBest(k=n_features,score_func=f_regression)),
        ("Regressor",regressor)
    ])

    negative_mse = cross_val_score(
        estimator=pipeline,
        X=X_train,
        y=y_train,
        cv=cv,
        scoring="neg_mean_squared_error",
        n_jobs=-1
    )

    return -negative_mse.mean()

In [46]:
study_random_forest = optuna.create_study(direction='minimize',sampler=optuna.samplers.TPESampler())
study_random_forest.optimize(lambda trial: objective(trial,regressor_name="RandomForest"),n_trials=30)

[I 2025-11-24 18:06:40,285] A new study created in memory with name: no-name-d10523ad-141a-43ba-8c60-2f47b21ec43c
[I 2025-11-24 18:06:45,108] Trial 0 finished with value: 0.5148786358801443 and parameters: {'n_features': 6, 'n_estimators': 165, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.5148786358801443.
[I 2025-11-24 18:06:48,053] Trial 1 finished with value: 0.5271935074689517 and parameters: {'n_features': 6, 'n_estimators': 91, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.5148786358801443.
[I 2025-11-24 18:06:55,101] Trial 2 finished with value: 0.5355347766169303 and parameters: {'n_features': 6, 'n_estimators': 199, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.5148786358801443.
[I 2025-11-24 18:07:01,134] Trial 3 finished with value: 0.4329902418964706 and parameters: {'n_features': 11, 'n_estimators': 128, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:08,368] Trial 4 finished with value: 0.4752999614645386 and parameters: {'n_features': 11, 'n_estimators': 213, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:16,919] Trial 5 finished with value: 0.4448155020012763 and parameters: {'n_features': 8, 'n_estimators': 215, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:19,201] Trial 6 finished with value: 0.4861501253935302 and parameters: {'n_features': 7, 'n_estimators': 75, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:22,905] Trial 7 finished with value: 0.49745482397321783 and parameters: {'n_features': 11, 'n_estimators': 128, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:24,362] Trial 8 finished with value: 0.5537868343832236 and parameters: {'n_features': 8, 'n_estimators': 73, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:28,152] Trial 9 finished with value: 0.5016851012868908 and parameters: {'n_features': 8, 'n_estimators': 159, 'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.4329902418964706.
[I 2025-11-24 18:07:34,083] Trial 10 finished with value: 0.4314741059654209 and parameters: {'n_features': 10, 'n_estimators': 295, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:39,396] Trial 11 finished with value: 0.43493179621034866 and parameters: {'n_features': 10, 'n_estimators': 283, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:44,469] Trial 12 finished with value: 0.4392409200362991 and parameters: {'n_features': 10, 'n_estimators': 293, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:45,130] Trial 13 finished with value: 0.6026320653836371 and parameters: {'n_features': 10, 'n_estimators': 123, 'max_depth': 3, 'min_samples_split': 13, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:48,585] Trial 14 finished with value: 0.47549178266707226 and parameters: {'n_features': 9, 'n_estimators': 238, 'max_depth': 18, 'min_samples_split': 18, 'min_samples_leaf': 3}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:52,489] Trial 15 finished with value: 0.4518998775684751 and parameters: {'n_features': 11, 'n_estimators': 249, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:54,362] Trial 16 finished with value: 0.47025578869814383 and parameters: {'n_features': 9, 'n_estimators': 133, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 4}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:56,264] Trial 17 finished with value: 0.43895867031754704 and parameters: {'n_features': 9, 'n_estimators': 105, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:59,024] Trial 18 finished with value: 0.457593541032853 and parameters: {'n_features': 10, 'n_estimators': 183, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:07:59,376] Trial 19 finished with value: 0.577337313215632 and parameters: {'n_features': 5, 'n_estimators': 52, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 2}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:03,528] Trial 20 finished with value: 0.45536394386078943 and parameters: {'n_features': 11, 'n_estimators': 262, 'max_depth': 18, 'min_samples_split': 17, 'min_samples_leaf': 5}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:09,076] Trial 21 finished with value: 0.43419312265310434 and parameters: {'n_features': 10, 'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:14,576] Trial 22 finished with value: 0.4334800730377267 and parameters: {'n_features': 10, 'n_estimators': 297, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:19,047] Trial 23 finished with value: 0.4383166578550345 and parameters: {'n_features': 9, 'n_estimators': 264, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:23,844] Trial 24 finished with value: 0.4337398229745393 and parameters: {'n_features': 11, 'n_estimators': 275, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:27,906] Trial 25 finished with value: 0.4445454635506124 and parameters: {'n_features': 10, 'n_estimators': 235, 'max_depth': 19, 'min_samples_split': 12, 'min_samples_leaf': 2}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:30,234] Trial 26 finished with value: 0.4601352911730719 and parameters: {'n_features': 9, 'n_estimators': 150, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 10 with value: 0.4314741059654209.
[I 2025-11-24 18:08:34,031] Trial 27 finished with value: 0.41084110587677153 and parameters: {'n_features': 11, 'n_estimators': 180, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 27 with value: 0.41084110587677153.
[I 2025-11-24 18:08:37,776] Trial 28 finished with value: 0.4149819157117688 and parameters: {'n_features': 11, 'n_estimators': 186, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 27 with value: 0.41084110587677153.
[I 2025-11-24 18:08:41,458] Trial 29 finished with value: 0.41684411884138683 and parameters: {'n_features': 11, 'n_estimators': 179, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 27 with value: 0.41084110587677153.

In [47]:
study_knn = optuna.create_study(direction='minimize',sampler=optuna.samplers.TPESampler())
study_knn.optimize(lambda trial: objective(trial,"KNN"),n_trials=30)

[I 2025-11-24 18:10:52,988] A new study created in memory with name: no-name-f0763650-95c4-4bf9-876f-ec7c0571b29c
[I 2025-11-24 18:10:53,051] Trial 0 finished with value: 0.6226420750782065 and parameters: {'n_features': 6, 'n_neighbors': 4}. Best is trial 0 with value: 0.6226420750782065.
[I 2025-11-24 18:10:53,114] Trial 1 finished with value: 0.5998893139111745 and parameters: {'n_features': 7, 'n_neighbors': 4}. Best is trial 1 with value: 0.5998893139111745.
[I 2025-11-24 18:10:53,166] Trial 2 finished with value: 0.5923823540678002 and parameters: {'n_features': 7, 'n_neighbors': 5}. Best is trial 2 with value: 0.5923823540678002.
[I 2025-11-24 18:10:53,228] Trial 3 finished with value: 0.5791087484837523 and parameters: {'n_features': 9, 'n_neighbors': 5}. Best is trial 3 with value: 0.5791087484837523.
[I 2025-11-24 18:10:53,300] Trial 4 finished with value: 0.5724714839011725 and parameters: {'n_features': 10, 'n_neighbors': 4}. Best is trial 4 with value: 0.5724714839011725.
[I 2025-11-24 18:10:53,374] Trial 5 finished with value: 0.5757517662956736 and parameters: {'n_features': 11, 'n_neighbors': 4}. Best is trial 4 with value: 0.5724714839011725.
[I 2025-11-24 18:10:53,449] Trial 6 finished with value: 0.5582893234874764 and parameters: {'n_features': 11, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,489] Trial 7 finished with value: 0.765147794258475 and parameters: {'n_features': 5, 'n_neighbors': 1}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,540] Trial 8 finished with value: 0.6998403949692494 and parameters: {'n_features': 9, 'n_neighbors': 1}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,591] Trial 9 finished with value: 0.6347412568364155 and parameters: {'n_features': 5, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,667] Trial 10 finished with value: 0.6330895277819157 and parameters: {'n_features': 11, 'n_neighbors': 2}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,741] Trial 11 finished with value: 0.5846121361300863 and parameters: {'n_features': 10, 'n_neighbors': 3}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,806] Trial 12 finished with value: 0.5846121361300863 and parameters: {'n_features': 10, 'n_neighbors': 3}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,883] Trial 13 finished with value: 0.5724714839011725 and parameters: {'n_features': 10, 'n_neighbors': 4}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:53,956] Trial 14 finished with value: 0.596358262456877 and parameters: {'n_features': 11, 'n_neighbors': 3}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,022] Trial 15 finished with value: 0.5791087484837523 and parameters: {'n_features': 9, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,075] Trial 16 finished with value: 0.5907489732076356 and parameters: {'n_features': 8, 'n_neighbors': 4}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,141] Trial 17 finished with value: 0.6144800068098146 and parameters: {'n_features': 10, 'n_neighbors': 2}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,215] Trial 18 finished with value: 0.5582893234874764 and parameters: {'n_features': 11, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,289] Trial 19 finished with value: 0.5582893234874764 and parameters: {'n_features': 11, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,343] Trial 20 finished with value: 0.5757290715243344 and parameters: {'n_features': 8, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,417] Trial 21 finished with value: 0.5582893234874764 and parameters: {'n_features': 11, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,491] Trial 22 finished with value: 0.5582893234874764 and parameters: {'n_features': 11, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,566] Trial 23 finished with value: 0.5582893234874764 and parameters: {'n_features': 11, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,630] Trial 24 finished with value: 0.5724714839011725 and parameters: {'n_features': 10, 'n_neighbors': 4}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,693] Trial 25 finished with value: 0.5791087484837523 and parameters: {'n_features': 9, 'n_neighbors': 5}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,756] Trial 26 finished with value: 0.596358262456877 and parameters: {'n_features': 11, 'n_neighbors': 3}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,818] Trial 27 finished with value: 0.5724714839011725 and parameters: {'n_features': 10, 'n_neighbors': 4}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,871] Trial 28 finished with value: 0.6512472601136388 and parameters: {'n_features': 8, 'n_neighbors': 2}. Best is trial 6 with value: 0.5582893234874764.
[I 2025-11-24 18:10:54,925] Trial 29 finished with value: 0.6226420750782065 and parameters: {'n_features': 6, 'n_neighbors': 4}. Best is trial 6 with value: 0.5582893234874764.

In [50]:
study_random_forest.best_params

{'n_features': 11,
 'n_estimators': 180,
 'max_depth': 17,
 'min_samples_split': 4,
 'min_samples_leaf': 1}

In [51]:
study_knn.best_params

{'n_features': 11, 'n_neighbors': 5}

In [59]:
print(f"RandomForest: {study_random_forest.best_value}")
print(f"KNN: {study_knn.best_value}")

if study_random_forest.best_value < study_knn.best_value:
    print("Random Forest wygrał")
else:
    print("KNN wygrał")

RandomForest: 0.41084110587677153
KNN: 0.5582893234874764
Random Forest wygrał

In [55]:
def get_scores(regressor_name,best_params):
    n_features = best_params['n_features']

    if regressor_name == "RandomForest":
        regressor = RandomForestRegressor(
            n_estimators=best_params['n_estimators'],
            max_depth=best_params['max_depth'],
            min_samples_split=best_params['min_samples_split'],
            min_samples_leaf=best_params['min_samples_leaf'],
            n_jobs=-1
        )
    elif regressor_name == "KNN":
        regressor = KNeighborsRegressor(
            n_neighbors=best_params['n_neighbors']
        )
    
    pipeline = Pipeline([
        ("StandardScaler",StandardScaler()),
        ("SelectKBest",SelectKBest(score_func=f_regression,k=n_features)),
        ('Regressor',regressor)
    ])

    scores = cross_validate(pipeline,X_train,y_train,cv=cv,scoring='neg_mean_squared_error')

    return -scores['test_score']

In [56]:
mse_rf = get_scores("RandomForest",study_random_forest.best_params)
mse_knn = get_scores("KNN",study_knn.best_params)

In [57]:
from scipy.stats import wilcoxon

In [60]:
stat,p_value = wilcoxon(mse_rf,mse_knn)

print(f"Różnica w wynikach wynosi: {abs(study_random_forest.best_value - study_knn.best_value)}")
print(f"p-value: {p_value}")

if p_value < 0.05:
    print("Różnica jest znacząca")
else:
    print("Nie ma różnicy")

Różnica w wynikach wynosi: 0.14744821761070487
p-value: 0.0625
Nie ma różnicy

In [63]:
best_rf_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ("SelectKBest", SelectKBest(k=study_random_forest.best_params["n_features"], score_func=f_regression)),
    ("Regressor", RandomForestRegressor(
        n_estimators=study_random_forest.best_params["n_estimators"],
        max_depth=study_random_forest.best_params["max_depth"],
        min_samples_split=study_random_forest.best_params["min_samples_split"],
        min_samples_leaf=study_random_forest.best_params["min_samples_leaf"]
    ))
])

In [65]:
best_rf_model.fit(X_train,y_train)

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('SelectKBest',
                 SelectKBest(k=11,
                             score_func=<function f_regression at 0x00000237D7224B80>)),
                ('Regressor',
                 RandomForestRegressor(max_depth=17, min_samples_split=4,
                                       n_estimators=180))])

In [66]:
y_pred = best_rf_model.predict(X_test)

In [67]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R²:", r2)

R²: 0.2967424775473303